name: nxp_originality_verifier
description: Dart package to veryify NXP tag originality against known or provided list of public keys
version: 0.0.5
homepage: https://github.com/aramix/nxp-originality-verifier

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  ecdsa: ^0.1.0
  elliptic: ^0.3.10

dev_dependencies:
  test: ^1.24.9
